[project]
name = "cargo_management"
description = "Package Tracker for Local Courier Services."
readme = "README.md"
license = {file = "LICENSE.txt"}
dynamic = ["version"]

requires-python = ">=3.10"

authors = [
    { name = "Agile Shift", email = "contacto@gruporeal.org" }
]

dependencies = [
    "easypost==7.10.0"
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"
